# Generated by Django 5.0.3 on 2024-04-17 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_sala_reserva_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='bookings.sala')),
            ],
        ),
    ]
